# Makefile

CXX = g++
CXXFLAGS = -std=c++11 -O2
TARGET = sorting_algorithms

all: $(TARGET)

$(TARGET): sorting_algorithms.cpp
	$(CXX) $(CXXFLAGS) -o $(TARGET) sorting_algorithms.cpp

clean:
	rm -f $(TARGET)
